### PR TITLE
fixed copy jsx bug

### PR DESCRIPTION
**Pull request by Anishpras**
@reinink  Here is a preview of the issue - 

https://user-images.githubusercontent.com/66175058/149278796-9830eda1-dce5-4f20-a4f5-5acd6cb291d5.mov

In both the cases, SVG is being copied.

### CODE REVIEW

**Comment by Anishpras** [comment]
@swanson an you please review this.

**Comment by swanson** [comment]
> @swanson can you please review this.

Hi, I'm not a maintainer of this project. One thing to note though is that there are a lot of changes to the file that don't seem related to the change you'd like to make (changing single quotes to double quotes for instance) that will likely prevent this from being merged.

**Comment by Anishpras** [comment]
> > @swanson can you please review this.
> 
> Hi, I'm not a maintainer of this project. One thing to note though is that there are a lot of changes to the file that don't seem related to the change you'd like to make (changing single quotes to double quotes for instance) that will likely prevent this from being merged.

@swanson I have removed all the unnecessary changes. Thank you for the valuable feedback.

**Comment by reinink** [comment]
Can you update the description of this PR to explain what it does? What was wrong with the current implementation?

**Comment by Anishpras** [comment]
> Can you update the description of this PR to explain what it does? What was wrong with the current implementation?

I have updated the description.

**Comment by reinink** [comment]
@Anishpras Hey, thanks for clearing things up for me. I understand what's going on now!

The "Copy JSX" button is intended for providing a JSX compatible version of the SVG code. You'll notice that the the JSX version uses `className` instead of `class`.

This option isn't intended to provide a React component snippet available via the `@heroicons/react`.

I hope that clears things up! 👍

**Comment by dan-klasson** [comment]
> This option isn't intended to provide a React component snippet available via the `@heroicons/react`.

So why can't you provide that?

**Pull request closed without merging**
